# Generated by Django 4.0.3 on 2022-06-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='food_items',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.fooditem'),
        ),
    ]
